apiVersion: apps/v1
kind: Deployment
metadata:
  name: voucher
  labels:
    app: voucher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voucher
  template:
    metadata:
      labels:
        app: voucher
    spec:
      containers:
        - name: voucher
          image: "user06.azurecr.io/voucher:v1"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "200m"  
          volumeMounts:
          - mountPath: "/mnt/data"
            name: volume
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: azurefile  

